- db/migrate/20220517225032_remove_vet_flag_from_users.rb
We don't need a boolean in the table.
> Removed vet_flag from User table.

- app/assets/stylesheets/components/_alert.scss
- app/assets/stylesheets/components/_avatar.scss
- app/assets/stylesheets/components/_chatroom.scss
- app/assets/stylesheets/components/_container.scss
- app/assets/stylesheets/components/_navbar.scss
To scss files container, navbar, avatar, chatroom and alert, I added the following : 
@media only screen
and (min-device-width: 375px)
and (max-device-width: 812px)
and (-webkit-min-device-pixel-ratio: 3) {
}
> add media query for mobile

- app/models/user.rb
- app/views/users/my_profile.html.erb
- db/seeds.rb
> Revert "Revert "seeding""

- app/controllers/consultations_controller.rb
- app/views/consultations/pet_consultations.html.erb
- app/views/shared/_my_pets.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
Can now access consultation history through the dropdown (for all) and through a pet (for specifics). The message history view is not implemented yet but I added a link to it on every consultation.
> consultation history

- app/controllers/users_controller.rb
- app/views/users/my_profile.html.erb
- config/routes.rb
> Availability status for vet can now be changed in the profile.

- app/assets/stylesheets/components/_chatroom.scss
- app/controllers/consultations_controller.rb
- app/controllers/messages_controller.rb
- app/controllers/users_controller.rb
- app/javascript/controllers/consultation_subscription_controller.js
- app/views/consultations/show.html.erb
- app/views/users/available_vets.html.erb
- config/routes.rb
- db/migrate/20220527000225_add_vet_to_consultations.rb
- db/schema.rb
- db/seeds.rb
Added Available vets list, connected consultations flow to chat, and fixed chat.
> Available vets list

- app/controllers/users_controller.rb
- app/models/user.rb
- app/views/shared/_navbar.html.erb
- app/views/users/edit.html.erb
- app/views/users/my_profile.html.erb
- config/routes.rb
- db/migrate/20220526234117_add_photo_to_users.rb
- db/migrate/20220527000348_remove_photo_from_users.rb
- db/schema.rb
Users can add or remove their profile picture
> profile pictures for users

- app/assets/config/manifest.js
- app/controllers/consultations_controller.rb
- app/controllers/feedbacks_controller.rb
- app/controllers/receipts_controller.rb
- app/views/feedbacks/new.html.erb
- app/views/receipts/show.html.erb
- app/views/shared/_pet_form.html.erb
- config/routes.rb
- db/migrate/20220528201127_add_columns_to_feedbacks.rb
- db/schema.rb
- Can either leave a feedback or skip the form after ending a consultation
> New feedback

- app/views/consultations/new.html.erb
> remove species input field for signed-in user with pet

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_button.scss
- app/javascript/packs/application.js
- app/javascript/plugins/init_star_rating.js
- app/models/feedback.rb
- app/views/feedbacks/new.html.erb
- package.json
- yarn.lock
- added yarn jquery-bar-rating for stars rating
> Survey form

- app/views/users/my_profile.html.erb
add btn that makes a vet avail/unavail. it's a draft.
> add avail/unavail btn that works. needs reworking though

- app/controllers/feedbacks_controller.rb
- app/controllers/receipts_controller.rb
- app/views/consultations/my_consultations.html.erb
- app/views/shared/_consultation_history.html.erb
- display only last 5 consults on my profile
- display all consults on My Consultations
- links to consultation leads to receipt
> My consultations

- app/assets/stylesheets/components/_consultation.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_signin.scss
- app/assets/stylesheets/components/_signup.scss
- app/views/consultations/my_consultations.html.erb
- app/views/consultations/new.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.html.erb
Centered and added media query to Sign up, Sign in, New consultation, my consultation
> added some style to the forms

- app/models/pet.rb
- app/models/specialty.rb
- app/views/consultations/my_consultations.html.erb
- app/views/shared/_consultation_history.html.erb
- db/seeds.rb
added more vets with picture
do not display consultations without receipts
> Seeds update

- app/assets/stylesheets/components/_card.scss
- app/views/consultations/my_consultations.html.erb
- styled my consultations page
- couldn't center the elements for desktop view with class="container-md". in chrome, it would make the texts in each car centered as well...
> Consult update

- app/models/feedback.rb
- app/views/messages/_message.html.erb
> Added validation for feedbacks + Dr. suffix & icon

- Gemfile
- Gemfile.lock
- app/controllers/consultations_controller.rb
- app/controllers/payments_controller.rb
- app/controllers/receipts_controller.rb
- app/models/consultation.rb
- app/services/stripe_checkout_session_service.rb
- app/views/consultations/my_consultations.html.erb
- app/views/payments/new.html.erb
- app/views/receipts/show.html.erb
- config/initializers/money.rb
- config/initializers/stripe.rb
- config/routes.rb
- db/migrate/20220607225628_add_price_to_consultations.rb
- db/schema.rb
- test/controllers/payments_controller_test.rb
> Initital stripe integration code.

- app/assets/stylesheets/components/_chatroom.scss
- app/assets/stylesheets/components/_consultation.scss
- app/javascript/controllers/dropdown_controller.js
- app/javascript/controllers/hello_controller.js
- app/views/consultations/show.html.erb
> Consult pin info

- app/views/users/available_vets.html.erb
> Added amount of reviews for each vet on vets list.

- app/controllers/application_controller.rb
- app/controllers/consultations_controller.rb
- app/controllers/feedbacks_controller.rb
- app/controllers/receipts_controller.rb
- Vet who responds gets redirected to the receipt when ending the consultation.
> vet side redirect

- app/assets/stylesheets/components/_card.scss
- app/views/users/available_vets.html.erb
> add text shadow to stars

- app/views/consultations/show.html.erb
> change words pinned at the top of chat

- db/seeds.rb
> remove pets for dr smith
